### ISSUE TITLE
Migrate Harbor from MariaDB to postgresql

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#4855]
- [x]  Code update, image update
- [x]  Migration scripts to migrate data from MariaDB to pgSQL 
- [x]  DB migrator image to support schema upgrade and DB migration on gpSQL

**Comment by mailzyok** [comment]
What is the usage of Mysql DB for harbor? I see comments in helm values.yaml
## MySQL Settings. Currently Harbor does not support an external
## MySQL server, only their own image. Until this is fixed, do not
## Change the settings below.
Thanks,
yzha
